In [5]:
from utils import RandomForest, get_columns, get_predict_clolumns

### 第一问

In [6]:
# 使用随机森林进
RF = RandomForest(
    train_file_path = '附件一（训练集）.xlsx',
    predict_file_path = '附件二（测试集）.xlsx',
    train_start_column_id = 4,
    predict_start_column_id = 4
)
selected_columns1, selected_columns2, selected_columns3, selected_columns4 = get_columns('附件一（训练集）.xlsx', 4)
predict1_column, predict2_column, predict3_column, predict4_column = get_predict_clolumns('附件二（测试集）.xlsx')


In [7]:
# 材料一
print(f"{predict1_column}")
# RF.train(selected_columns1)
y_pred1 = RF.predict(selected_columns1, predict1_column, "材料1")
y_pred1


    0（磁通密度B，T）         1         2         3         4         5         6  \
0    -0.101398 -0.099219 -0.097045 -0.094873 -0.092701 -0.090534 -0.088371   
1    -0.031775 -0.031081 -0.030391 -0.029704 -0.029019 -0.028333 -0.027647   
2    -0.066871 -0.065300 -0.063737 -0.062185 -0.060640 -0.059101 -0.057567   
3    -0.023190 -0.022634 -0.022084 -0.021540 -0.020998 -0.020455 -0.019912   
4    -0.077613 -0.075852 -0.074096 -0.072348 -0.070611 -0.068883 -0.067162   
5    -0.011507 -0.011253 -0.011001 -0.010750 -0.010497 -0.010244 -0.009993   
6    -0.035798 -0.035013 -0.034231 -0.033448 -0.032664 -0.031883 -0.031100   
7    -0.027493 -0.026872 -0.026253 -0.025635 -0.025018 -0.024401 -0.023785   
8    -0.033539 -0.032832 -0.032128 -0.031422 -0.030721 -0.030026 -0.029331   
9    -0.020561 -0.020113 -0.019667 -0.019221 -0.018774 -0.018332 -0.017891   
10    0.001771  0.001986  0.002201  0.002417  0.002632  0.002847  0.003063   
11   -0.000822 -0.000518 -0.000214  0.000090  0.000395  0.000699

d:\miniforge3\envs\study\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [8]:
# 材料二
print(f"{predict2_column}")
# RF.train(selected_columns2)
y_pred2 = RF.predict(selected_columns2, predict2_column, "材料2")
y_pred2

    0（磁通密度B，T）         1         2         3         4         5         6  \
20   -0.028317 -0.027692 -0.027073 -0.026460 -0.025851 -0.025242 -0.024632   
21   -0.033840 -0.033438 -0.033036 -0.032636 -0.032237 -0.031841 -0.031447   
22   -0.036583 -0.036308 -0.036038 -0.035772 -0.035508 -0.035244 -0.034980   
23   -0.028852 -0.028536 -0.028225 -0.027916 -0.027610 -0.027305 -0.026998   
24   -0.119871 -0.119028 -0.118192 -0.117364 -0.116541 -0.115718 -0.114895   
25    0.000847  0.000998  0.001149  0.001300  0.001450  0.001601  0.001751   
26    0.000850  0.001000  0.001150  0.001300  0.001450  0.001600  0.001750   
27   -0.017610 -0.017892 -0.018172 -0.018452 -0.018731 -0.019009 -0.019287   
28    0.006521  0.006607  0.006693  0.006778  0.006864  0.006949  0.007034   
29   -0.082748 -0.083078 -0.083403 -0.083725 -0.084046 -0.084363 -0.084677   
30   -0.026493 -0.026300 -0.026109 -0.025918 -0.025726 -0.025534 -0.025344   
31   -0.011289 -0.011162 -0.011037 -0.010912 -0.010787 -0.010663

d:\miniforge3\envs\study\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [9]:
# 材料三
print(f"{predict3_column}")
# RF.train(selected_columns3)
y_pred3 = RF.predict(selected_columns3, predict3_column, "材料3")
y_pred3


    0（磁通密度B，T）         1         2         3         4         5         6  \
40   -0.012409 -0.012127 -0.011844 -0.011562 -0.011281 -0.011001 -0.010723   
41   -0.029958 -0.029793 -0.029628 -0.029463 -0.029300 -0.029137 -0.028974   
42   -0.010474 -0.010397 -0.010321 -0.010246 -0.010170 -0.010094 -0.010019   
43   -0.046128 -0.045645 -0.045161 -0.044679 -0.044200 -0.043724 -0.043248   
44   -0.043167 -0.042866 -0.042566 -0.042267 -0.041970 -0.041675 -0.041381   
45    0.000326  0.000519  0.000712  0.000904  0.001097  0.001290  0.001482   
46   -0.000284 -0.000208 -0.000132 -0.000056  0.000021  0.000097  0.000173   
47    0.000199  0.000320  0.000440  0.000560  0.000681  0.000801  0.000921   
48   -0.000920 -0.000770 -0.000620 -0.000460 -0.000310 -0.000160 -0.000010   
49    0.032130  0.031980  0.031830  0.031680  0.031530  0.031370  0.031220   
50   -0.056724 -0.055490 -0.054264 -0.053046 -0.051835 -0.050624 -0.049411   
51   -0.038111 -0.037840 -0.037571 -0.037304 -0.037039 -0.036778

array([[False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [10]:
# 材料4
print(f"{predict4_column}")
# RF.train(selected_columns4)
y_pred4 = RF.predict(selected_columns4, predict4_column, "材料4")
y_pred4


    0（磁通密度B，T）         1         2         3         4         5         6  \
60   -0.095988 -0.093812 -0.091650 -0.089495 -0.087349 -0.085205 -0.083068   
61   -0.047009 -0.046495 -0.045991 -0.045490 -0.044991 -0.044494 -0.043999   
62   -0.092695 -0.091702 -0.090716 -0.089733 -0.088755 -0.087781 -0.086808   
63   -0.019388 -0.018936 -0.018492 -0.018052 -0.017613 -0.017175 -0.016738   
64   -0.079803 -0.078004 -0.076231 -0.074480 -0.072747 -0.071027 -0.069312   
65   -0.023390 -0.022817 -0.022249 -0.021688 -0.021133 -0.020582 -0.020035   
66   -0.059101 -0.058474 -0.057854 -0.057237 -0.056620 -0.056002 -0.055387   
67   -0.035044 -0.034239 -0.033443 -0.032661 -0.031886 -0.031115 -0.030343   
68   -0.034367 -0.033559 -0.032768 -0.031987 -0.031210 -0.030433 -0.029659   
69   -0.262161 -0.259374 -0.256622 -0.253879 -0.251149 -0.248417 -0.245685   
70   -0.061466 -0.061242 -0.061022 -0.060803 -0.060586 -0.060369 -0.060153   
71   -0.019290 -0.018843 -0.018397 -0.017954 -0.017511 -0.017069

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [12]:
import numpy as np
# 将它们依次拼接
y_pred_combined = np.concatenate((y_pred1, y_pred2, y_pred3, y_pred4), axis=0)

# 结果的形状
print(y_pred_combined.shape)  
print(y_pred_combined)

(80, 3)
[[ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [Fal

In [19]:
# 进行映射
output = np.zeros(y_pred_combined.shape[0], dtype=int)
output[np.all(y_pred_combined == [True, False, False], axis=1)] = 2  # 对应 [1,0,0] 三角
output[np.all(y_pred_combined == [False, True, False], axis=1)] = 3  # 对应 [0,1,0] 梯形
output[np.all(y_pred_combined == [False, False, True], axis=1)] = 1  # 对应 [0,0,1] 正弦

print(output)


[2 2 2 2 2 3 3 3 3 3 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 3 3 3 3 3 2 2
 2 2 2 3 2 3 3 3 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 2
 2 1 1 1 1 1]


In [21]:
from collections import Counter

count = Counter(output)

# 打印结果
print(count)

Counter({np.int64(2): 44, np.int64(1): 20, np.int64(3): 16})


In [22]:
#三角波44                   1表示正弦波，2表示三角波，3表示梯形波
#正弦20
#梯形16

In [23]:
# 写入附件4 第二列
import pandas as pd
df = pd.read_excel('附件四（Excel表）.xlsx')

# 将 output 列表转换为 DataFrame
output_df = pd.DataFrame(output, columns=['Values'])

# 将输出写入 DataFrame 的第二列
df.iloc[:len(output), 1] = output_df['Values']

# 将更新后的 DataFrame 保存回 Excel
df.to_excel('附件四（Excel表）.xlsx', index=False)
