In [5]:
import numpy as np
from utils import read_column_from_excel, get_onehot_labels, get_columns, \
                  MultiLinearRegression, PolynomialRegression, \
                  get_mean, get_std, max, min, peak_to_peak
                  
                  

In [6]:
# 获取磁通密度
(
    selected_columns1, 
    selected_columns2, 
    selected_columns3, 
    selected_columns4 
 ) = get_columns('附件一（训练集）.xlsx', 4)

# 从第四列开始向后（下标从0开始）
selected_columns1

0（磁通密度B，T）         1         2         3         4         5         6  \
0       0.000213  0.000389  0.000566  0.000743  0.000919  0.001096  0.001272   
1      -0.000551 -0.000358 -0.000165  0.000028  0.000221  0.000413  0.000605   
2      -0.003780 -0.003564 -0.003349 -0.003134 -0.002919 -0.002704 -0.002488   
3      -0.000511 -0.000267 -0.000023  0.000222  0.000466  0.000711  0.000955   
4       0.000458  0.000732  0.001007  0.001281  0.001555  0.001830  0.002104   
...          ...       ...       ...       ...       ...       ...       ...   
3395   -0.014217 -0.013898 -0.013582 -0.013266 -0.012951 -0.012634 -0.012318   
3396   -0.017910 -0.017508 -0.017108 -0.016711 -0.016312 -0.015912 -0.015514   
3397   -0.020028 -0.019578 -0.019130 -0.018684 -0.018237 -0.017790 -0.017343   
3398   -0.027652 -0.027021 -0.026392 -0.025764 -0.025138 -0.024513 -0.023888   
3399   -0.030905 -0.030196 -0.029490 -0.028785 -0.028082 -0.027380 -0.026679   

             7         8         9  ...      1014      1015      1016  \
0     0.001448  0.001624  0.001800  ... -0.001551 -0.001374 -0.001198   
1     0.000798  0.000991  0.001183  ... -0.002476 -0.002284 -0.002091   
2    -0.002273 -0.002057 -0.001841  ... -0.005927 -0.005713 -0.005499   
3     0.001199  0.001443  0.001687  ... -0.002950 -0.002707 -0.002463   
4     0.002378  0.002653  0.002927  ... -0.002290 -0.002016 -0.001741   
...        ...       ...       ...  ...       ...       ...       ...   
3395 -0.012005 -0.011694 -0.011383  ... -0.016320 -0.016200 -0.016076   
3396 -0.015119 -0.014727 -0.014335  ... -0.020542 -0.020390 -0.020234   
3397 -0.016900 -0.016460 -0.016019  ... -0.023021 -0.022852 -0.022679   
3398 -0.023266 -0.022644 -0.022025  ... -0.032188 -0.031942 -0.031679   
3399 -0.025981 -0.025284 -0.024589  ... -0.036009 -0.035732 -0.035434   

          1017      1018      1019      1020      1021      1022      1023  
0    -0.001022 -0.000846 -0.000669 -0.000492 -0.000316 -0.000140  0.000036  
1    -0.001899 -0.001707 -0.001515 -0.001322 -0.001129 -0.000937 -0.000744  
2    -0.005285 -0.005070 -0.004855 -0.004640 -0.004425 -0.004210 -0.003995  
3    -0.002220 -0.001976 -0.001732 -0.001488 -0.001244 -0.001000 -0.000756  
4    -0.001466 -0.001192 -0.000917 -0.000642 -0.000367 -0.000092  0.000183  
...        ...       ...       ...       ...       ...       ...       ...  
3395 -0.015945 -0.015797 -0.015620 -0.015403 -0.015143 -0.014849 -0.014537  
3396 -0.020069 -0.019883 -0.019663 -0.019394 -0.019070 -0.018703 -0.018312  
3397 -0.022491 -0.022278 -0.022022 -0.021709 -0.021337 -0.020920 -0.020478  
3398 -0.031381 -0.031029 -0.030602 -0.030094 -0.029522 -0.028912 -0.028285  
3399 -0.035096 -0.034697 -0.034213 -0.033641 -0.032999 -0.032315 -0.031613  

[3400 rows x 1024 columns]

In [7]:
# 处理磁通密度特征
mean1 = get_mean(selected_columns1)
mean2 = get_mean(selected_columns2)
mean3 = get_mean(selected_columns3)
mean4 = get_mean(selected_columns4)

std_value1 = get_std(selected_columns1)
std_value2 = get_std(selected_columns2)
std_value3 = get_std(selected_columns3)
std_value4 = get_std(selected_columns4)

max1 = max(selected_columns1)
max2 = max(selected_columns2)
max3 = max(selected_columns3)
max4 = max(selected_columns4)

min1 = min(selected_columns1)
min2 = min(selected_columns2)
min3 = min(selected_columns3)
min4 = min(selected_columns4)

peak1 = peak_to_peak(selected_columns1)
peak2 = peak_to_peak(selected_columns2)
peak3 = peak_to_peak(selected_columns3)
peak4 = peak_to_peak(selected_columns4)

peak4

array([0.05180628, 0.06381334, 0.07107428, ..., 0.0968109 , 0.10876936,
       0.13690633])

In [9]:
temperature1 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料1")
wave_shape1 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料1")
material1_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料1")

temperature2 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料2")
wave_shape2 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料2")
material2_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料2")

temperature3 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料3")
wave_shape3 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料3")
material3_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料3")

temperature4 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料4")
wave_shape4 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料4")
material4_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料4")


In [10]:
material1_hz

0        50030
1        50020
2        50020
3        50020
4        50030
         ...  
3395    316460
3396    316460
3397    316460
3398    316460
3399    316460
Name: 频率，Hz, Length: 3400, dtype: int64

In [11]:
# 创建四个 one-hot 矩阵 以表示材料特征
one_hot_matrix1 = np.zeros((3400, 4))       # 材料1 [1, 0, 0, 0]
one_hot_matrix1[:, 0] = 1  

one_hot_matrix2 = np.zeros((3000, 4))       # 材料2 [0, 1, 0, 0]
one_hot_matrix2[:, 1] = 1  

one_hot_matrix3 = np.zeros((3200, 4))
one_hot_matrix3[:, 2] = 1  

one_hot_matrix4 = np.zeros((2800, 4))
one_hot_matrix4[:, 3] = 1  

print(one_hot_matrix1)
# 拼接 
x1 = np.column_stack((temperature1, wave_shape1, one_hot_matrix1, material1_hz, max1, min1, std_value1, peak1, mean1))
x2 = np.column_stack((temperature2, wave_shape2, one_hot_matrix2, material2_hz, max2, min2, std_value2, peak2, mean2))
x3 = np.column_stack((temperature3, wave_shape3, one_hot_matrix3, material3_hz, max3, min3, std_value3, peak3, mean3))
x4 = np.column_stack((temperature4, wave_shape4, one_hot_matrix4, material4_hz, max4, min4, std_value4, peak4, mean4))

# 拼接输入矩阵
X_combined = np.vstack((x1, x2, x3, x4))
X_combined.shape

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


(12400, 14)

**拼接标签数据**

In [12]:
y1 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料1')
y2 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料2')
y3 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料3')
y4 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料4')
y4.shape

(2800,)

In [35]:
y_combined = np.concatenate((y1, y2, y3, y4))
y_combined.shape

(12400,)

### 训练

1. **使用多元线性回归**

In [42]:

from sklearn.model_selection import train_test_split
# 多元逻辑回归
mlr = MultiLinearRegression()
X = X_combined
Y = y_combined

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)



# 评估结果
# 拟合
mlr.fit(X_train, Y_train)
# 评估
score = mlr.score(X_test, Y_test)
print(f"Model R² score: {score}")
Y.shape

Model R² score: 0.6354522047500337


(12400,)

2. **支持向量机回归**


3. **神经网络**


4. **多项式回归**

In [43]:
from utils import PolynomialRegression

plR = PolynomialRegression()

plR.fit(X_train, Y_train)
mse, r2  = plR.evaluate(X_test, Y_test)

# 打印结果
print(f'MSE: {mse:.4f}, R²: {r2:.4f}')

MSE: 7870773627.6498, R²: 0.9415


In [44]:
import numpy as np
from sklearn.model_selection import KFold
from utils import PolynomialRegression

# 初始化模型
plR = PolynomialRegression()

# 定义 KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)  # 5 折交叉验证

mse_list = []
r2_list = []

# 进行交叉验证
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    plR.fit(X_train, Y_train)
    mse, r2 = plR.evaluate(X_test, Y_test)
    
    mse_list.append(mse)
    r2_list.append(r2)

# 计算平均值
mean_mse = np.mean(mse_list)
mean_r2 = np.mean(r2_list)

# 打印结果
print(f'Mean MSE: {mean_mse:.4f}, Mean R²: {mean_r2:.4f}')


Mean MSE: 8364928532.1001, Mean R²: 0.9409
