In [1]:
import numpy as np
import pandas as pd
from utils import read_column_from_excel, get_onehot_labels, get_columns, \
                  MultiLinearRegression, PolynomialRegression, \
                  get_mean, get_std, max, min, peak_to_peak
                  
                  

In [2]:
# 获取磁通密度
(
    selected_columns1, 
    selected_columns2, 
    selected_columns3, 
    selected_columns4 
 ) = get_columns('附件一（训练集）.xlsx', 4)

# 从第四列开始向后（下标从0开始）
selected_columns1

0（磁通密度B，T）         1         2         3         4         5         6  \
0       0.000213  0.000389  0.000566  0.000743  0.000919  0.001096  0.001272   
1      -0.000551 -0.000358 -0.000165  0.000028  0.000221  0.000413  0.000605   
2      -0.003780 -0.003564 -0.003349 -0.003134 -0.002919 -0.002704 -0.002488   
3      -0.000511 -0.000267 -0.000023  0.000222  0.000466  0.000711  0.000955   
4       0.000458  0.000732  0.001007  0.001281  0.001555  0.001830  0.002104   
...          ...       ...       ...       ...       ...       ...       ...   
3395   -0.014217 -0.013898 -0.013582 -0.013266 -0.012951 -0.012634 -0.012318   
3396   -0.017910 -0.017508 -0.017108 -0.016711 -0.016312 -0.015912 -0.015514   
3397   -0.020028 -0.019578 -0.019130 -0.018684 -0.018237 -0.017790 -0.017343   
3398   -0.027652 -0.027021 -0.026392 -0.025764 -0.025138 -0.024513 -0.023888   
3399   -0.030905 -0.030196 -0.029490 -0.028785 -0.028082 -0.027380 -0.026679   

             7         8         9  ...      1014      1015      1016  \
0     0.001448  0.001624  0.001800  ... -0.001551 -0.001374 -0.001198   
1     0.000798  0.000991  0.001183  ... -0.002476 -0.002284 -0.002091   
2    -0.002273 -0.002057 -0.001841  ... -0.005927 -0.005713 -0.005499   
3     0.001199  0.001443  0.001687  ... -0.002950 -0.002707 -0.002463   
4     0.002378  0.002653  0.002927  ... -0.002290 -0.002016 -0.001741   
...        ...       ...       ...  ...       ...       ...       ...   
3395 -0.012005 -0.011694 -0.011383  ... -0.016320 -0.016200 -0.016076   
3396 -0.015119 -0.014727 -0.014335  ... -0.020542 -0.020390 -0.020234   
3397 -0.016900 -0.016460 -0.016019  ... -0.023021 -0.022852 -0.022679   
3398 -0.023266 -0.022644 -0.022025  ... -0.032188 -0.031942 -0.031679   
3399 -0.025981 -0.025284 -0.024589  ... -0.036009 -0.035732 -0.035434   

          1017      1018      1019      1020      1021      1022      1023  
0    -0.001022 -0.000846 -0.000669 -0.000492 -0.000316 -0.000140  0.000036  
1    -0.001899 -0.001707 -0.001515 -0.001322 -0.001129 -0.000937 -0.000744  
2    -0.005285 -0.005070 -0.004855 -0.004640 -0.004425 -0.004210 -0.003995  
3    -0.002220 -0.001976 -0.001732 -0.001488 -0.001244 -0.001000 -0.000756  
4    -0.001466 -0.001192 -0.000917 -0.000642 -0.000367 -0.000092  0.000183  
...        ...       ...       ...       ...       ...       ...       ...  
3395 -0.015945 -0.015797 -0.015620 -0.015403 -0.015143 -0.014849 -0.014537  
3396 -0.020069 -0.019883 -0.019663 -0.019394 -0.019070 -0.018703 -0.018312  
3397 -0.022491 -0.022278 -0.022022 -0.021709 -0.021337 -0.020920 -0.020478  
3398 -0.031381 -0.031029 -0.030602 -0.030094 -0.029522 -0.028912 -0.028285  
3399 -0.035096 -0.034697 -0.034213 -0.033641 -0.032999 -0.032315 -0.031613  

[3400 rows x 1024 columns]

In [3]:
# 处理磁通密度特征
mean1 = get_mean(selected_columns1)
mean2 = get_mean(selected_columns2)
mean3 = get_mean(selected_columns3)
mean4 = get_mean(selected_columns4)

std_value1 = get_std(selected_columns1)
std_value2 = get_std(selected_columns2)
std_value3 = get_std(selected_columns3)
std_value4 = get_std(selected_columns4)

max1 = max(selected_columns1)
max2 = max(selected_columns2)
max3 = max(selected_columns3)
max4 = max(selected_columns4)

min1 = min(selected_columns1)
min2 = min(selected_columns2)
min3 = min(selected_columns3)
min4 = min(selected_columns4)

peak1 = peak_to_peak(selected_columns1)
peak2 = peak_to_peak(selected_columns2)
peak3 = peak_to_peak(selected_columns3)
peak4 = peak_to_peak(selected_columns4)

peak4

array([0.05180628, 0.06381334, 0.07107428, ..., 0.0968109 , 0.10876936,
       0.13690633])

In [4]:
temperature1 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料1")
wave_shape1 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料1")
material1_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料1")

temperature2 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料2")
wave_shape2 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料2")
material2_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料2")

temperature3 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料3")
wave_shape3 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料3")
material3_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料3")

temperature4 = read_column_from_excel('附件一（训练集）.xlsx', column_name="温度，oC", sheet_name="材料4")
wave_shape4 = get_onehot_labels('附件一（训练集）.xlsx', column_name="励磁波形", name="材料4")
material4_hz = read_column_from_excel('附件一（训练集）.xlsx', column_name="频率，Hz", sheet_name="材料4")


In [5]:
material1_hz

0        50030
1        50020
2        50020
3        50020
4        50030
         ...  
3395    316460
3396    316460
3397    316460
3398    316460
3399    316460
Name: 频率，Hz, Length: 3400, dtype: int64

In [6]:
# 创建四个 one-hot 矩阵 以表示材料特征
one_hot_matrix1 = np.zeros((3400, 4))       # 材料1 [1, 0, 0, 0]
one_hot_matrix1[:, 0] = 1  

one_hot_matrix2 = np.zeros((3000, 4))       # 材料2 [0, 1, 0, 0]
one_hot_matrix2[:, 1] = 1  

one_hot_matrix3 = np.zeros((3200, 4))
one_hot_matrix3[:, 2] = 1  

one_hot_matrix4 = np.zeros((2800, 4))
one_hot_matrix4[:, 3] = 1  

print(one_hot_matrix1)
# 拼接 
x1 = np.column_stack((temperature1, wave_shape1, one_hot_matrix1, material1_hz, max1, min1, std_value1, peak1, mean1))
x2 = np.column_stack((temperature2, wave_shape2, one_hot_matrix2, material2_hz, max2, min2, std_value2, peak2, mean2))
x3 = np.column_stack((temperature3, wave_shape3, one_hot_matrix3, material3_hz, max3, min3, std_value3, peak3, mean3))
x4 = np.column_stack((temperature4, wave_shape4, one_hot_matrix4, material4_hz, max4, min4, std_value4, peak4, mean4))

# 拼接输入矩阵
X_combined = np.vstack((x1, x2, x3, x4))
X_combined.shape

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


(12400, 14)

**拼接标签数据**

In [7]:
y1 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料1')
y2 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料2')
y3 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料3')
y4 = read_column_from_excel('附件一（训练集）.xlsx', column_name='磁芯损耗，w/m3', sheet_name='材料4')
print(y4)
y4.shape

0         2525.795337
1         4427.524958
2         5780.576037
3        10983.412600
4        14526.685680
            ...      
2795     20604.900210
2796     26504.284280
2797     46232.491530
2798     61458.085900
2799    107581.189300
Name: 磁芯损耗，w/m3, Length: 2800, dtype: float64


(2800,)

In [8]:
y_combined = np.concatenate((y1, y2, y3, y4))
y_combined

array([  1997.95525,   2427.74983,   3332.72576, ...,  46232.49153,
        61458.0859 , 107581.1893 ])

### 训练

1. **使用多元线性回归**

In [9]:

from sklearn.model_selection import train_test_split
# 多元逻辑回归
mlr = MultiLinearRegression()
X = X_combined
Y = y_combined

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)



# 评估结果
# 拟合
mlr.fit(X_train, Y_train)
# 评估
score = mlr.score(X_test, Y_test)
print(f"Model R² score: {score}")
Y.shape

Model R² score: 0.6354522047500337


(12400,)

2. **支持向量机回归**


3. **神经网络**


4. **多项式回归**

In [41]:
from utils import PolynomialRegression

plR = PolynomialRegression(alpha=10.0)

plR.fit(X_train, Y_train)
mse, r2  = plR.evaluate(X_test, Y_test)

# 打印结果
print(f'MSE: {mse:.4f}, R²: {r2:.4f}')



MSE: 11824779445.5354, R²: 0.9089


d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=9.18591e-26): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


In [42]:
# 输出多项式系数
coefficients = plR.model.coef_
intercept = plR.model.intercept_

# 构建多项式表达式
polynomial = f"{intercept:.2f}"
for i in range(1, len(coefficients)):
    if coefficients[i] != 0:
        polynomial += f" + {coefficients[i]:.2f} * x^{i}"

print("生成的多项式表达式:")
print(polynomial)

生成的多项式表达式:
-88016.42 + -382.57 * x^1 + -17041.12 * x^2 + -20196.40 * x^3 + 37237.52 * x^4 + 16587.90 * x^5 + -7589.38 * x^6 + -30206.28 * x^7 + 21207.75 * x^8 + -0.19 * x^9 + -6397.50 * x^10 + 7562.55 * x^11 + -2987.44 * x^12 + -13960.04 * x^13 + -0.00 * x^14 + 18.81 * x^15 + 135.95 * x^16 + -97.04 * x^17 + -421.48 * x^18 + -79.41 * x^19 + -158.66 * x^20 + -84.09 * x^21 + -60.41 * x^22 + -0.00 * x^23 + 25273.02 * x^24 + 50911.43 * x^25 + 81343.62 * x^26 + -25638.41 * x^27 + -0.05 * x^28 + -17041.12 * x^29 + 19280.43 * x^32 + -22480.16 * x^33 + -26251.36 * x^34 + 12409.98 * x^35 + -0.06 * x^36 + 30631.79 * x^37 + -24381.89 * x^38 + 16210.48 * x^39 + 55013.68 * x^40 + -0.00 * x^41 + -20196.40 * x^42 + -19659.93 * x^44 + 1299.51 * x^45 + -7863.40 * x^46 + 6027.42 * x^47 + 0.01 * x^48 + 41605.10 * x^49 + -43808.65 * x^50 + 35070.83 * x^51 + 85413.74 * x^52 + 0.00 * x^53 + 37237.52 * x^54 + 16967.41 * x^55 + 13591.27 * x^56 + 3908.49 * x^57 + 2770.35 * x^58 + -0.12 * x^59 + -78634.38 * x^60

In [43]:
import numpy as np
from sklearn.model_selection import KFold
from utils import PolynomialRegression

# 初始化模型
plR = PolynomialRegression()

# 定义 KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)  # 5 折交叉验证

mse_list = []
r2_list = []

# 进行交叉验证
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    plR.fit(X_train, Y_train)
    mse, r2 = plR.evaluate(X_test, Y_test)
    
    mse_list.append(mse)
    r2_list.append(r2)

# 计算平均值
mean_mse = np.mean(mse_list)
mean_r2 = np.mean(r2_list)

# 打印结果
print(f'Mean MSE: {mean_mse:.4f}, Mean R²: {mean_r2:.4f}')


Mean MSE: 8744993624.8580, Mean R²: 0.9382


d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=8.82085e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=8.74346e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=8.71518e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=8.63455e-27): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_ridge.py:21

## 使用附件三进行预测

In [44]:
from utils import get_onehot_labels
material = get_onehot_labels("附件三（测试集）.xlsx", "磁芯材料", "测试集")
material = material.astype(float)
print(material)


     材料1  材料2  材料3  材料4
0    1.0  0.0  0.0  0.0
1    1.0  0.0  0.0  0.0
2    1.0  0.0  0.0  0.0
3    1.0  0.0  0.0  0.0
4    1.0  0.0  0.0  0.0
..   ...  ...  ...  ...
395  0.0  0.0  0.0  1.0
396  0.0  0.0  0.0  1.0
397  0.0  0.0  0.0  1.0
398  0.0  0.0  0.0  1.0
399  0.0  0.0  0.0  1.0

[400 rows x 4 columns]


In [45]:
type(material)

pandas.core.frame.DataFrame

In [46]:
# 获取磁通密度
df = pd.read_excel('附件三（测试集）.xlsx')
selected_columns = df.iloc[:,  5: ]

# 处理磁通密度特征
mean = get_mean(selected_columns)

std_value = get_std(selected_columns)

max_values = max(selected_columns)

min_values = min(selected_columns)

peak = peak_to_peak(selected_columns)

temperature = read_column_from_excel('附件三（测试集）.xlsx', column_name="温度，oC", sheet_name="测试集")
wave_shape = get_onehot_labels('附件三（测试集）.xlsx', column_name="励磁波形", name="测试集")
material_hz = read_column_from_excel('附件三（测试集）.xlsx', column_name="频率，Hz", sheet_name="测试集")

x_question4 = np.column_stack((temperature, wave_shape, material, material_hz, max_values, min_values, std_value, peak, mean))



In [47]:
print(x_question4)
x_question4.shape

[[25.          0.          0.         ...  0.04423171  0.12520859
   0.        ]
 [25.          0.          0.         ...  0.044172    0.12482856
  -0.        ]
 [25.          0.          0.         ...  0.04972267  0.14052946
  -0.        ]
 ...
 [90.          0.          1.         ...  0.0837919   0.2727724
  -0.        ]
 [90.          0.          1.         ...  0.08347612  0.27182239
   0.        ]
 [90.          0.          1.         ...  0.00664378  0.02169404
  -0.        ]]


(400, 14)

### 使用多元线性回归预测

In [48]:
np.set_printoptions(suppress=True)  # 关闭科学计数法
predict_results = mlr.predict(x_question4)
print(predict_results)

# 保留一位小数
results =  np.round(predict_results, 1)
print("保留一位小数:")
print(results)



[ -40336.01438751  -13663.44250761   27598.53641925   10242.17587323
   72600.25172562  -42810.60395297  -85218.92234537  -73601.20317216
  341247.28666589   73182.81751736  -10908.59198048  366442.14438201
 -122602.73477272 -130495.99875608    2756.90860076  -86354.45246296
  158477.81323477  283055.60338712  -22799.9514317   391012.24767302
 -208296.28853304   97778.6841643   505761.16862351  -88181.41093606
   -1080.72978795  -21185.06833398  204072.21779915  304807.76009585
 -176349.59123746  534467.00231499 -125750.23404304 -151642.29590352
   26377.47579498   63826.38001645    9377.86531077   17391.07944304
  134224.13228934  161816.01484342  207517.09393204  362309.20879682
  319186.23489366 1021440.07915613 1121672.1283667   757067.10457511
 -130108.28211117    3872.96583774   -8376.28453333  370471.89015353
  -62385.36245462  119043.93820632 -157733.60582732   43226.8669577
  -45721.80987553  159063.56304686  145150.69384868  785601.28955866
  474154.17517289  145521.99682439 

### 使用多项式回归预测

In [49]:

PlR_results = plR.predict(x_question4)
print(PlR_results)

# 保留一位小数
results2 =  np.round(PlR_results, 1)
print("保留一位小数:")
print(results2)

[  -3111.46662967   15207.70539561   25932.30645702   33027.76423872
   49648.49276828   29992.28692774    4808.21995613  -10180.07146516
  434356.73239577  -32663.28510116  -39515.96290985  134761.23078871
   14986.32650007   13282.00019749   32153.58564359  -39808.78544525
  156046.49397883  314007.81767112  -74244.5336808   538508.48702322
   41458.60945761  -27628.40594103  284548.85040749     860.81096292
   -8928.59869362    4921.35083125  209094.65829725  392710.64980211
   23991.27541301  517909.18889104   34172.58157491   26407.93956425
   34063.88592983   74414.42429461  -96873.99919862  -85704.31471138
   20025.05682904  186847.68119474  229725.55192879  546357.67766396
   54877.33902796  966910.14076936  813648.79963066  702010.61967963
  -37986.91261842   41601.71337529  -10027.92017394  579482.54945692
   15014.39316161  117735.70674361   25651.6895851   104622.70142249
  -64986.46225543   33926.42683632 -150151.90928733  279592.22473981
  147348.52581917  249296.24141976

In [50]:

results2

array([  -3111.5,   15207.7,   25932.3,   33027.8,   49648.5,   29992.3,
          4808.2,  -10180.1,  434356.7,  -32663.3,  -39516. ,  134761.2,
         14986.3,   13282. ,   32153.6,  -39808.8,  156046.5,  314007.8,
        -74244.5,  538508.5,   41458.6,  -27628.4,  284548.9,     860.8,
         -8928.6,    4921.4,  209094.7,  392710.6,   23991.3,  517909.2,
         34172.6,   26407.9,   34063.9,   74414.4,  -96874. ,  -85704.3,
         20025.1,  186847.7,  229725.6,  546357.7,   54877.3,  966910.1,
        813648.8,  702010.6,  -37986.9,   41601.7,  -10027.9,  579482.5,
         15014.4,  117735.7,   25651.7,  104622.7,  -64986.5,   33926.4,
       -150151.9,  279592.2,  147348.5,  249296.2,   88105.9,  100319.2,
        205413.1,  254163.4,   83739.3,  227155.8,  -80448.7,  323952.6,
         21763.2,  449185.9,  842760.7,  437706.5,  -10306.1,   -5707.8,
        506834.5,  -24469.5,  315522.9, 1400012.8,  -18502.8,  -83781.5,
        -83546. ,   -2274.2,  376233.1,  314987.3, 

##  Lasso 回归

In [51]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score





In [52]:
from utils import LassoRegressionModel
# 创建模型实例
lasso_model = LassoRegressionModel(alpha=0.5)

# 假设 X 和 y 是你的特征和标签数据
lasso_model.fit(X_train, Y_train)
# 进行预测
predictions = lasso_model.predict(X_test)

lasso_model.evaluate(X_test, Y_test)


# 获取特征系数
coefficients = lasso_model.get_coefficients()
print("Coefficients:", coefficients)

# 获取评估指标
metrics = lasso_model.get_metrics()
print("MSE:", metrics['MSE'])
print("R²:", metrics['R²'])

Coefficients: [    -1276.38964135    -41977.5220532     -32919.49338366
     18359.96916258    -34659.4714705     -15340.57535052
     11163.16278131         2.38038347         1.22512703
   4815819.13205932     33733.21950935 -12636831.27279304
   3934904.73577217        -0.        ]
MSE: 47036303075.91624
R²: 0.6376750576112347


d:\miniforge3\envs\study\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.580e+14, tolerance: 1.434e+11
  model = cd_fast.enet_coordinate_descent(


In [53]:
# 获取特征系数
coefficients = lasso_model.get_coefficients()

# 输出特征及其系数
feature_names = ['温度', '波形1', '波形2', '波形3', '材料1', '材料2','材料3','材料4','material_hz', 'max_values', \
                 'min_values', 'std_value', 'peak', 'mean']  # 以你的特征名称替换
for feature, coef in zip(feature_names, coefficients):
    print(f"Feature: {feature}, Coefficient: {coef}")

Feature: 温度, Coefficient: -1276.3896413502864
Feature: 波形1, Coefficient: -41977.52205320266
Feature: 波形2, Coefficient: -32919.49338366397
Feature: 波形3, Coefficient: 18359.969162578724
Feature: 材料1, Coefficient: -34659.47147049648
Feature: 材料2, Coefficient: -15340.57535051657
Feature: 材料3, Coefficient: 11163.162781310712
Feature: 材料4, Coefficient: 2.380383472683118
Feature: material_hz, Coefficient: 1.2251270305513742
Feature: max_values, Coefficient: 4815819.132059321
Feature: min_values, Coefficient: 33733.219509354145
Feature: std_value, Coefficient: -12636831.272793043
Feature: peak, Coefficient: 3934904.7357721734
Feature: mean, Coefficient: -0.0


In [54]:
lasso_model.predict(x_question4)

array([ -39177.2958107 ,  -12506.77078022,   28112.53289837,
         11645.67348268,   73134.68820083,  -40467.24896869,
        -81786.12697234,  -70034.98091955,  340817.85855375,
         76791.50624337,  -10351.45980051,  359518.98774873,
       -119674.21132118, -127194.68778883,    5055.63110709,
        -82581.5448596 ,  159889.96834605,  282930.39618622,
        -18951.94607776,  390234.56325474, -205619.06564803,
         96551.89338383,  494279.20429671,  -86423.94845995,
          -610.35640734,  -19706.21861334,  206113.0297098 ,
        305698.39698858, -174029.24959882,  527002.49778657,
       -122553.86490774, -148065.57328442,   29600.56989745,
         66706.73244378,   13475.98441153,   21419.87585025,
        141273.84667625,  166289.5838081 ,  213000.66490845,
        371260.31050073,  323135.1534396 , 1028160.29503653,
       1143720.22826778,  772775.33869435, -129979.40888555,
          5755.26949976,   -7631.84336616,  379350.05211424,
        -61365.16121442,